name: 'Main Workflow'

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'

jobs:

  deploy_tag:
    name: Deploy tag
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits), '[skip ci]') == false

    steps:

      - uses: actions/setup-go@v4
        with:
          go-version: '1.17.0'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set tag env
        run: |
          ref=${GITHUB_REF#refs/*/}
          if [ $ref = master ]; then
            tag=latest
          else
            tag=$ref
          fi
          echo "RELEASE_VERSION=$tag" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kubemod/kubemod:${{ env.RELEASE_VERSION}}

      - name: Codecov
        if: ${{ env.RELEASE_VERSION == 'latest' }}
        run: bash <(curl -s https://codecov.io/bash)